# Random Forest

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

importing the dataset

In [2]:
dataset=pd.read_csv('Position_Salaries.csv')
x = dataset.iloc[:, 1:-1].values # level
y = dataset.iloc[:, -1].values # salary
x,y

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]], dtype=int64),
 array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
         300000,  500000, 1000000], dtype=int64))

TRAINING DECISION TREE MODEL

In [9]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(x,y)

RandomForestRegressor(n_estimators=10, random_state=2)

PREDICT NEW VALUE

In [6]:
y_pred=regressor.predict([[6.5]])
y_pred

array([167000.])